collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4517544
  brandStrength: 0.6712632
  lightness: 0.4310777
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.6766917
typography_spectrum: 0.4805765
layout_spectrum: 0.3847118
name: uiuxdesigner
