layout_spectrum: 0.9467419
typography_spectrum: 0.4805765
color:
  saturation: 0.6110914
  lightness: 0.5821066
  brandStrength: 0.6712632
  rhythmicContrast: 0.4584896
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: uiuxdesigner
